name: Build
on:
  schedule:
    - cron: '2 2 * * 2'
  workflow_dispatch:
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        repository: riscv-collab/riscv-gnu-toolchain
    - name: Install deps
      run: sudo apt install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
    - name: Run configure
      run: sudo ./configure --prefix=/opt/riscv/ --enable-multilib
    - name: Run make
      run: sudo make -j$(nproc --all)
    - name: Strip executables
      run: sudo find /opt/riscv/ -executable -type f -exec strip {} ;
    - name: Compress artifacts
      run: sudo tar -c -I 'xz -9 -T0' -f riscv-gnu-toolchain-linux.tar.xz /opt/riscv/
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        path: riscv-gnu-toolchain-linux.tar.xz

  # build-windows:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       repository: riscv-collab/riscv-gnu-toolchain
  #   - name: Install deps
  #     run: sudo apt install mingw-w64 autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
  #   - name: Run configure
  #     run: sudo ./configure --host=x86_64-w64-mingw32 --prefix=/opt/riscv/ --enable-multilib
  #   - name: Run make
  #     run: sudo make -j$(nproc --all)
  #   - name: Strip executables
  #     run: sudo find /opt/riscv/ -executable -type f -exec strip {} ;
  #   - name: Compress artifacts
  #     run: sudo tar -c -I 'xz -9 -T0' -f riscv-gnu-toolchain-windows.tar.xz /opt/riscv/
  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v2.2.4
  #     with:
  #       path: riscv-gnu-toolchain-windows.tar.xz
